# site settings
title: COdeDEmon
subtitle: by Ritwik Raj Singh
email: ritwikrajdhangta@gmail.com
description: It's a responsive site designed using HTML5 <br /> for personal blogs and projects.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ritwik Raj Singh
street_address: 1234, Somewhere on Road
city: Shimla
state: Himachal Pradesh
zip_code: 171204
country: India
phone: (+91) 8580595318

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: http://github.com/Ritwikrajsingh
gitlab_url: https://gitlab.com/Ritwikrajsingh
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/ritwik-raj-s-189562132
pinterest_url:
slack_url:
twitter_url: https://twitter.com/RitwikRajSingh2
whatsapp_url: https://wa.me/919459415700

# build settings
markdown: kramdown

sass:
  style: compressed
